version: '3'
services:
  samba:
    build: samba
    image: samba
    container_name: samba
    ports:
      - 139:139
      - 445:445
    volumes:
      - /home/master:/home/master
    restart: always
